/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetiredContentRouteImport } from './routes/retired-content'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CoffeeIndexRouteImport } from './routes/coffee/index'
import { Route as CoffeeSlugRouteImport } from './routes/coffee/$slug'
import { Route as NaBeersIndexRouteImport } from './routes/na-beers/index'
import { Route as NaBeersSlugRouteImport } from './routes/na-beers/$slug'
import { Route as ReubensIndexRouteImport } from './routes/reubens/index'
import { Route as ReubensSlugRouteImport } from './routes/reubens/$slug'
import { Route as WingsIndexRouteImport } from './routes/wings/index'
import { Route as WingsSlugRouteImport } from './routes/wings/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiredContentRoute = RetiredContentRouteImport.update({
  id: '/retired-content',
  path: '/retired-content',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeIndexRoute = CoffeeIndexRouteImport.update({
  id: '/coffee/',
  path: '/coffee/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeSlugRoute = CoffeeSlugRouteImport.update({
  id: '/coffee/$slug',
  path: '/coffee/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NaBeersIndexRoute = NaBeersIndexRouteImport.update({
  id: '/na-beers/',
  path: '/na-beers/',
  getParentRoute: () => rootRouteImport,
} as any)
const NaBeersSlugRoute = NaBeersSlugRouteImport.update({
  id: '/na-beers/$slug',
  path: '/na-beers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReubensIndexRoute = ReubensIndexRouteImport.update({
  id: '/reubens/',
  path: '/reubens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReubensSlugRoute = ReubensSlugRouteImport.update({
  id: '/reubens/$slug',
  path: '/reubens/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WingsIndexRoute = WingsIndexRouteImport.update({
  id: '/wings/',
  path: '/wings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WingsSlugRoute = WingsSlugRouteImport.update({
  id: '/wings/$slug',
  path: '/wings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/retired-content': typeof RetiredContentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coffee/$slug': typeof CoffeeSlugRoute
  '/na-beers/$slug': typeof NaBeersSlugRoute
  '/reubens/$slug': typeof ReubensSlugRoute
  '/wings/$slug': typeof WingsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/coffee/': typeof CoffeeIndexRoute
  '/na-beers/': typeof NaBeersIndexRoute
  '/reubens/': typeof ReubensIndexRoute
  '/wings/': typeof WingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/retired-content': typeof RetiredContentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coffee/$slug': typeof CoffeeSlugRoute
  '/na-beers/$slug': typeof NaBeersSlugRoute
  '/reubens/$slug': typeof ReubensSlugRoute
  '/wings/$slug': typeof WingsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/coffee': typeof CoffeeIndexRoute
  '/na-beers': typeof NaBeersIndexRoute
  '/reubens': typeof ReubensIndexRoute
  '/wings': typeof WingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/retired-content': typeof RetiredContentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coffee/$slug': typeof CoffeeSlugRoute
  '/na-beers/$slug': typeof NaBeersSlugRoute
  '/reubens/$slug': typeof ReubensSlugRoute
  '/wings/$slug': typeof WingsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/coffee/': typeof CoffeeIndexRoute
  '/na-beers/': typeof NaBeersIndexRoute
  '/reubens/': typeof ReubensIndexRoute
  '/wings/': typeof WingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/retired-content'
    | '/blog/$slug'
    | '/coffee/$slug'
    | '/na-beers/$slug'
    | '/reubens/$slug'
    | '/wings/$slug'
    | '/blog/'
    | '/coffee/'
    | '/na-beers/'
    | '/reubens/'
    | '/wings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/retired-content'
    | '/blog/$slug'
    | '/coffee/$slug'
    | '/na-beers/$slug'
    | '/reubens/$slug'
    | '/wings/$slug'
    | '/blog'
    | '/coffee'
    | '/na-beers'
    | '/reubens'
    | '/wings'
  id:
    | '__root__'
    | '/'
    | '/retired-content'
    | '/blog/$slug'
    | '/coffee/$slug'
    | '/na-beers/$slug'
    | '/reubens/$slug'
    | '/wings/$slug'
    | '/blog/'
    | '/coffee/'
    | '/na-beers/'
    | '/reubens/'
    | '/wings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RetiredContentRoute: typeof RetiredContentRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoffeeSlugRoute: typeof CoffeeSlugRoute
  NaBeersSlugRoute: typeof NaBeersSlugRoute
  ReubensSlugRoute: typeof ReubensSlugRoute
  WingsSlugRoute: typeof WingsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoffeeIndexRoute: typeof CoffeeIndexRoute
  NaBeersIndexRoute: typeof NaBeersIndexRoute
  ReubensIndexRoute: typeof ReubensIndexRoute
  WingsIndexRoute: typeof WingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retired-content': {
      id: '/retired-content'
      path: '/retired-content'
      fullPath: '/retired-content'
      preLoaderRoute: typeof RetiredContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee/': {
      id: '/coffee/'
      path: '/coffee'
      fullPath: '/coffee/'
      preLoaderRoute: typeof CoffeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee/$slug': {
      id: '/coffee/$slug'
      path: '/coffee/$slug'
      fullPath: '/coffee/$slug'
      preLoaderRoute: typeof CoffeeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/na-beers/': {
      id: '/na-beers/'
      path: '/na-beers'
      fullPath: '/na-beers/'
      preLoaderRoute: typeof NaBeersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/na-beers/$slug': {
      id: '/na-beers/$slug'
      path: '/na-beers/$slug'
      fullPath: '/na-beers/$slug'
      preLoaderRoute: typeof NaBeersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reubens/': {
      id: '/reubens/'
      path: '/reubens'
      fullPath: '/reubens/'
      preLoaderRoute: typeof ReubensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reubens/$slug': {
      id: '/reubens/$slug'
      path: '/reubens/$slug'
      fullPath: '/reubens/$slug'
      preLoaderRoute: typeof ReubensSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wings/': {
      id: '/wings/'
      path: '/wings'
      fullPath: '/wings/'
      preLoaderRoute: typeof WingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wings/$slug': {
      id: '/wings/$slug'
      path: '/wings/$slug'
      fullPath: '/wings/$slug'
      preLoaderRoute: typeof WingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RetiredContentRoute: RetiredContentRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoffeeSlugRoute: CoffeeSlugRoute,
  NaBeersSlugRoute: NaBeersSlugRoute,
  ReubensSlugRoute: ReubensSlugRoute,
  WingsSlugRoute: WingsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoffeeIndexRoute: CoffeeIndexRoute,
  NaBeersIndexRoute: NaBeersIndexRoute,
  ReubensIndexRoute: ReubensIndexRoute,
  WingsIndexRoute: WingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
